### ISSUE TITLE
Blog Posts Not In Order

### ISSUE THREAD

**Issue by ardalis** [ardalis/ardalis-com-gatsby#1262]
On the /blog page the posts are showing things from 15+ years ago at the top of the list:
![image](https://user-images.githubusercontent.com/782127/82976404-fad9f200-9fac-11ea-86b7-c7f38927a390.png)

These should be in order by the date on the document, descending.

**Comment by emmadigital** [comment]
Thats just temporary, I will revert it back to descending order in my next deploy.

**Comment by ardalis** [comment]
Thanks! I'm going to mention an article on the new site in my newsletter that goes out to 3000 people in 2 hours, so hopefully the site's mostly working (and the article is published).

**Comment by ardalis** [comment]
FYI, I updated gatsby-node.js to boost the limit from 1000 to 10,000.

**Comment by ardalis** [comment]
Seems helpful - adding for future reference:
https://developer.okta.com/blog/2020/02/18/gatsby-react-netlify

**Comment by emmadigital** [comment]
Thanks for sharing. ☺

I have updated below changes you requested and also all blog posts are
updated too. You're good to go for launch now. Once you point to new
domain, I will update the Google Analytics plugin as well:


   1. Add Publish date to category page
   2. Remove Square label "blogging" from blog post page
   3. Change Background of square label over headerimage on all pages
   4. Install Prism Plugin for Code Block Styling
   5. Mailchimp Configured - *Please test before launch*

**Comment by ardalis** [comment]
I'm good to launch now? Yay!

So it sounds like all I need to do is point ardalis.com at the new location (for which I will probably move my DNS hosting over to Netlify entirely).

Your 5 things listed above you will do after I update DNS? Or what is the plan for those?

**Comment by ardalis** [comment]
Looking at the Blog tab now, these 4 posts are NOT from May 2020:
![image](https://user-images.githubusercontent.com/782127/83158716-1f2fee80-a0d3-11ea-8cb1-284a347cd526.png)

I haven't checked further, but it's important that the publish dates match what they were previously in WordPress after this migration. Can you please double-check and correct? Thanks!

**Comment by ardalis** [comment]
I'm going to try and create separate issues for each task we both have so that we can track them individually and close this one.
