### ISSUE TITLE
Display (and sort by) Publish Date on Category Page

### ISSUE THREAD

**Issue by ardalis** [ardalis/ardalis-com-gatsby#1289]
Category pages should include the post's publish date.
![image](https://user-images.githubusercontent.com/782127/83159573-1f7cb980-a0d4-11ea-9a9c-9fda5b4d5c1a.png)

(I think this is done and working - please confirm there's nothing more to do here)

**Comment by emmadigital** [comment]
It has been updated please check

**Comment by ardalis** [comment]
Looks good.
