### ISSUE TITLE
Install and Configure Prism Plugin for code block styling

### ISSUE THREAD

**Issue by ardalis** [ardalis/ardalis-com-gatsby#1290]
Here's an example code block:
![image](https://user-images.githubusercontent.com/782127/83159772-5bb01a00-a0d4-11ea-8d35-348e1eca17f7.png)

I'm guessing it should look a bit better than this once Prism is working properly.

Looking at Prism Themes, I think the Okaidia (dark) one looks good:
https://prismjs.com/examples.html

I'm not sure where that would be set but if you can do that easily and make sure it's working everywhere and/or tell me what I need to do to get it working that would be great!

**Comment by emmadigital** [comment]
I have changed the default prism theme to the one you requested **Okaidia (dark)**, which as a default gives this look https://beta.ardalis.com/great-uses-of-using-statement-in-c/ but if you add specific language suchas csharp, javascript, python etc.. like this https://prnt.sc/sppiuf to all of your code blocks inside markdown file then you can get below look:
https://beta.ardalis.com/configuring-logging-in-azure-app-services/
https://beta.ardalis.com/listing-strongly-typed-enum-options-in-c/

**Comment by ardalis** [comment]
That looks good, thanks. I can worry about specifying the language in the individual posts.

If I want to adjust prism's settings where is the theme set?

I found this in `gatsby-browser.js` but I don't think this is everything, is it?
`require("prismjs/themes/prism-okaidia.css")`

**Comment by emmadigital** [comment]
if you want to set another theme then you change it here. For theme settings you mean background or text color then you need to modify  style.css

**Comment by ardalis** [comment]
I mean theme. It's fine, I'm happy with this one for now.
