### ISSUE TITLE
Update DNS and Go Live

### ISSUE THREAD

**Issue by ardalis** [ardalis/ardalis-com-gatsby#1296]
Steve:

- Move DNS hosting to Netlify
- Update Ardalis.com to point to Netlify endpoint

See https://docs.netlify.com/domains-https/custom-domains/
and https://www.netlify.com/blog/2020/03/26/how-to-set-up-netlify-dns-custom-domains-cname-a-records/

Emma:

- Add Google Analytics to the site

**Comment by emmadigital** [comment]
You can just create a CNAME record with your DNS provider as defined here https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/#configure-a-subdomain as it will not effect your current email settings.

**Comment by ardalis** [comment]
I finished migrating the images and I've updated DNS. It will take some time to propagate, but ardalis.com should show the new netlify site now/soon.

If you haven't already, can you update/add google analytics to the netlify/gatsby site? Where in the source is that done? Thanks @emmadigital !

**Comment by ardalis** [comment]
FYI I'm working on getting analytics working.

**Comment by emmadigital** [comment]
> I finished migrating the images and I've updated DNS. It will take some time to propagate, but ardalis.com should show the new netlify site now/soon.
> 
> If you haven't already, can you update/add google analytics to the netlify/gatsby site? Where in the source is that done? Thanks @emmadigital !

I can see the new site, congrats! have you started google analytics configuration or should I do it for you?

**Comment by ardalis** [comment]
I think I've got it. trying to fix various warnings and get support for animated gif featureimage right now.

**Comment by ardalis** [comment]
I still can't run locally. I get lots of these:
error There was an error in your GraphQL query:

Field "image" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" make sure that your input source and/or plugin is correct.
error There was an error in your GraphQL query:

Field "image" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" make sure that your input source and/or plugin is correct.
error There was an error in your GraphQL query:

**Comment by ardalis** [comment]
when I hit it on localhost i see:
![image](https://user-images.githubusercontent.com/782127/83792991-e01d1280-a669-11ea-9cb6-48bd98aa8aa3.png)

**Comment by emmadigital** [comment]
Just run gatsby clean 4 - 5 times the error will go away.  Its basically because of the image path locally it can't locate.

**Comment by ardalis** [comment]
running it once doesn't do it? that's... annoying.

**Comment by ardalis** [comment]
`netlify dev` runs `gatsby clean` every time so not sure why this should help but trying it...

Same error the first time.

Should we just modify our build locally to map /img to /static/img ?

**Comment by emmadigital** [comment]
Then you have to change it for all posts but when you add a new post Netlify CMS will again set the same path as /img . most of the time I never get this error but sometime it appears may be because of the cache so i have to clean it so it disappears.

**Comment by ardalis** [comment]
I've cleaned over and over but haven't yet gotten it to work once locally.

I've spent hours on this now today. Sigh.

Are you running Windows or Mac/Linux? I wonder if that makes a difference, since it seems to work on Netlify's remote machines.

**Comment by emmadigital** [comment]
I am using windows

**Comment by ardalis** [comment]
Ok, thanks. I tried using WSL linux but didn't get any further. It just concerns me that something will break on Netlify's end and I won't be able to diagnose or fix it because I can't run gatsby locally.

**Comment by ardalis** [comment]
Site seems to be working on the new host/dns!
