### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by ardalis** [ardalis/ardalis-com-gatsby#1305]
I thought I could get it working by adding a plug-in but it doesn't appear to have worked. My stats are 0 now. Can you help?

**Comment by emmadigital** [comment]
Updated google analytics new plugin https://www.gatsbyjs.org/packages/gatsby-plugin-google-gtag/?=gta let me know the stats. This plugin is better than the previous one.

**Comment by ardalis** [comment]
when you're making updates can you use pull requests are at least normal commits (after doing a pull to get latest)? I think you overwrote all of my commits with your update.

**Comment by emmadigital** [comment]
Sorry for the trouble. I cloned your latest repo and pushed the changes I made it. 

How is your analytics working?

**Comment by ardalis** [comment]
I ended up using Google Tag Manager and associated gatsby plugin. I hadn't used GTM before but it seems to be working:

![image](https://user-images.githubusercontent.com/782127/84051794-9e4bdf00-a97d-11ea-96ca-89a2db88351f.png)
