### ISSUE TITLE
Create a Grocerylist

### ISSUE THREAD

**Issue by BikerMouse** [ardalis/ardalis-com-gatsby#1642]
## Feature request

**What is the expected behavior?**
As a user I want to create a list with items which I need to by doing groceries.

**What is motivation or use case for adding/changing the behavior?**
First feature op the app.

**How should this be implemented in your opinion?**
The correct way 😆 

**Are you willing to work on this yourself?**
yes

**Comment by ardalis** [comment]
I'm not sure this repo is what you think it is...

**Comment by BikerMouse** [comment]
This is so embarrassing!

I was trying out issues but somehow it got in your repository. My sincere
apologies.

Obviously you may remove them.

Kind regards,
Sander

**Comment by ardalis** [comment]
No worries 😃
